version: "3.3"
services:
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=jade123
      - MYSQL_DATABASE=webAppDatabase

  cache:
    image: redis:7.0.0
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  "web-application":
    build: "./web-application"
    ports:
      - "3000:8080"
      - "9229:9229"
      - "3002:3002"
    depends_on:
      - database
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - database
      - cache
    volumes:
      - "./web-application/src:/web-application/src"

  spa:
    build: "./spa"
    ports:
      - 3001:3001
    volumes:
      - "./spa/src:/spa/src"
    depends_on:
      - database
      - web-application

volumes:
  database:
    driver: local
  cache:
    driver: local
